

#+Revision: 0
#+Audience: LEWGI
#+Status: 
#+Group: WG21
#+Title: A proposal to add process management to the C++ standard library
#+Author: 
#+Email: jeff@crystalclearsoftware.com

* Revision History
** Revision 0
Initial release.

* Introduction

The creation and management of processes is a widely used and fundamental tool in computing systems.  Unfortunately C++ does not have a portable way to create and manage processes.  Most other langauge standard libraries support facilities to wrap the complexities in support of application programmers.   The functionality has been on standard library wishlists going back to 2007 (Matt Austern ref below).

The proposal is based on boost.process https://www.boost.org/libs/process which provides cross-platform implementation experience.

* Motivation and Scope

We propose a library to facilitate the following basic functionality:
+    create child processes on the current machine
+    setup streams for communication with child std::out and std::err
+    communicate with child processes through streams
+    wait for processes to exit 
+    terminate processes
+    capture the return result of a child process
+    manage groups of processes
+    optionally associate the child-process to the parent-child to children die with their parents, but not vice-versa.

The following illustrates an example usage of the proposed library. 

#+BEGIN_SRC c++

#include <process>

int main()
{

  std::vector<std::string> args { "--version", "--std=c++2a" };

  try {
    std::ipstream pipe_stream;
    std::process child("gcc", args, std::proccess_io({}, pipe_stream, {})); //capture std::out, leave the others as the OS defaults

    std::string line;

    while (pipe_stream && std::getline(pipe_stream, line) && !line.empty()) 
    {
        std::cerr << line << std::endl;
    }
    child.wait();
  }
  catch(const std::exception& e) 
  {
     std::cerr << e.what();
  }
}

#+END_SRC

* Domain Terminology
** Processes
A process is an instance of a program in execution. A process has at least one thread. A process starts execution in the thread that invokes it's main function.  A child process is the result of another process creating or spawning the child. 

** Process Groups
Process groups allow for managing a set of processes at the operating system level. This allows behavior such as process termination to be automatically coordinated by the operating system.  For example, child processes in a group can be set to terminate together.

** Pipes
A pipe is a unidirectional, serial communication line across processes. A pipe has two ends: a write end and a read end.

A pipe is buffered. The size of the buffer is implementation defined. When there's no data in the buffer, the pipe is called empty. When the buffer is full, the pipe is called full.

Reading from an empty pipe is a blocking operation. Writing to a pipe resumes any blocked threads that are waiting to read on that pipe.

Writing to a full pipe is a blocking operation. Reading from a pipe resumes any blocked threads that are writing to that pipe.

If there are multiple threads reading or writing from the same pipe at the same time the order in which they read the data is unspecified.

** Environment and Command Line Arguments

Creation of a child process sometimes involves modifying the environment for the child process.  This proposal references a current proposal for referencing a process environment.  However, the proposal in P1275 would need to be enhance to support multiple instances of environments for access and modification of child process environment.

Isabella Muerte Desert Sessions: Improving hostile environment interactions http://wg21.link/p1275

* Use Cases
* Survey of facilities in other standard libraries
** C/C++ system function

C and C++ currently provide a minimal process launching capability via the `system` function. The C++ function takes a =const char*= parameter that represents command string to execute and an integer return code that signifies the execution return status. 

#+BEGIN_SRC c++

  int result = system("echo \"foo\" > bar.txt");
  if (result == 0) {
    //do something
#+END_SRC

This minimal facility lacks many aspects of process control needed for even basic applications including access to the std::err and std::out of the child.

#+BEGIN_SRC c++
template<typename ...Args>
inline int system(Args && ... args)
{
    std::process c(std::forward<Args>(args)...,);
    if (!c.valid())
        return -1;
    c.wait();
    return c.exit_code();
}
#+END_SRC

** Java
Java provides a ProcessBuilder and stream piping facilities similar to what is proposed here. 

#+BEGIN_SRC java

// ProcessBuilder takes variadic string arguments
// or a List<String>
var builder = new ProcessBuilder("/bin/cat", "-");

// start()-method will spawn the process
// Standard streams are piped automatically
Process p = builder.start();

// Write into process stdin
new OutputStreamWriter(p.getOutputStream())
      .write("foo\n")
      .close(); // close() needed to flush the buffer

// Read from stdout
var reader = new BufferedReader(
                  new InputStreamReader(p.getInputStream()));
String output = reader.readLine();

assert output == "foo";

System.out.println("Exited with " + p.exitValue())

#+END_SRC

** Python

#+BEGIN_SRC python
from subprocess import Popen, PIPE

# Command line arguments are all passed in a single list
# Standard streams aren't piped by default
child = Popen([ '/bin/cat', '-' ],
          stdin=PIPE, stdout=PIPE, stderr=PIPE)

# communicate() takes input (optional)
# Waits for process to terminate
# Handles to standard streams aren't available
out, err = child.communicate(input='foo\n')
assert out == 'foo'
print("Exited with", child.returncode)

#+END_SRC

** Rust
As with other languages Rust provides the ability to pipe the results of the process into the parent.

#+BEGIN_SRC rust
use std::process::{Command, Stdio};

let mut child = Command("/bin/cat")
                .arg("-") // .args() also available, taking a range
                          // strings passed to .arg() are escaped
                .stdin(Stdio::piped())
                .stdout(Stdio::piped())
                .spawn()?; // ?-operator is for error handling
child.stdin.as_mut()?.write_all(b"foo\n")?;
// .wait_with_output() will, well, wait
// child.stdout/stderr exposes standard streams directly
let output = child.wait_with_output()?;
assert_eq!(b"foo", output.stdout.as_slice());
println!("Exited with {}", output.status.code.unwrap());

#+END_SRC

** Nodejs
Nodejs offers the functionality through a package with similar functions to other langauges.

#+BEGIN_SRC js

const { spawn } = require('child_process');

// First argument is argv[0], rest of argv passed in a list
const p = spawn('/bin/cat', ['-']);
p.stdin.write('foo\n');
// Idiomatic node.js uses callbacks everywhere
p.stdout.on('data', (data) => {
  assert.StrictEqual(data, 'foo\n');
});
p.on('close', (code) => {
  console.log(`Exited with ${code}`);
});

#+END_SRC
* Design 
** Process Concepts

** Core language impact
Bryce to provide information to Jeff
** Header <process>
** Namespace std:: versus std::process

The classes and functions for this proposal could be put into namespace std:: or sub namespace such as std::process. Process is more similar to thread than filesystem.  Since thread is in namespace std this proposal suggests the same for process.

** Start of execution on process create
** Using a builder method to create
Have a run() method versus immediate in the constructor

** Handling of parameters
  - There's an issue of escaping the argument properly
  - see issues below on 1275
** ~wait~ or ~join~
** Native Operating System Handle

The solution provides access to the operating system like std::thread for programmers that which to go beyond the provided facilities.

** Portable callbacks during spawn
*** onError -- does this change into a non-exception
*** onSuccess
*** onSetup
** EOF on pipe close
** Security and User Management Implications

** Error Handling

** Synchronous Versus Asynchronous

** Integration of iostreams and pipes

* Technical Specification
** Header ~<process>~ Synopsis

This is a first cut at th wording. We probably don't need to go much deeper in the specification than the synopsis for the first paper.  I (Jeff G) basically lifted this out of boost.process::child and updated.

#+BEGIN_SRC c++
 
namespace std {

   //A launcher is an object that has a launch function that takes a path, arguments and a variadic list of process initializers and returns a process object. 
   template<typename T>
   concept bool ProcessLauncher = requires(T launcher) {
           {launcher.set_error(error_code(), "message")} -> void; //so initializers can post internal errors
           {launcher.launch(filesystem::path(), vector<string>())} -> process; //refine that so check tha parameter list, good enough for now.
   };
   
   //An initializer is an object that changes the behavior of a process during launch and thus listens to at least one of the hooks of the launcher. 
   //Note that the following example only uses portable hooks, but non portables might suffic as well
   template<typename Init, ProcessLauncher Launcher = process_launcher>
   concept bool ProcessInitializer =
           requires(Init initializer, Launcher launcher) { {initializer.on_setup(launcher)}   -> void;}
        || requires(Init initializer, Launcher launcher) { {initializer.on_success(launcher)} -> void; }
        || requires(Init initializer, Launcher launcher) { {initializer.on_error(launcher, error_code())} -> void; };
   }

   // A Pid type is an identifier for a process, that satisfies StrictTotallyOrdered
   using pid_type = implementation-defined;
   

   //Process satisfies Movable & Boolean, but not Copyable.

   //Provides a portable handle to an operating system process
   class process;
   
   //Provides a portable wrapper for a process group
   class process_group;
   
   //Provides an initializers for the standard io. Alternative: nested as std::process::io
   class process_io;
   
   //Provides a way to set the starting directory of the new process.  Alternative: nested as std::process::start_dir
   class process_start_dir;

}
#+END_SRC


** Class ~process~

#+BEGIN_SRC c++
class process
{
  public:
    //provides access to underlying operating system facilities
    typedef platform_specific native_handle_type; 

    // Construct a child from a property list and launch it.
    template<ProcessInitializer ...Inits>
    explicit process(const std::filesystem::path & exe, const Range<std::string> & args, Inits&&...inits);

    // Construct a child from a property list and launch it with a custom process launcher
    template<ProcessInitializer ...Inits, ProcessLauncher Launcher>
    explicit process(const std::filesystem::path & exe, const Range<std::string> & args, Inits&&...inits, Launcher && launcher);


    // Attach to an existing process
    explicit process(pid_type & pid);

    // An empty process is similar to a default constructed thread. It holds an empty handle and is a place holder for a process that is to be launched later.
    process() = default;

    process(process && lhs);
    process& operator=(process && lhs);
 
    
    // The destructor terminates 
    ~process();

    // Accessors 

    pid_type id()      const;

    native_handle_type native_handle() const;

    // return code of the process, only valid if !running()
    int exit_code() const;


    // check if the process is running. If the process has exited already, it might store the exit_code internally.
    bool running() const;

    /** Check if this handle holds a child process.
     * @note That does not mean, that the process is still running. It only means, that the handle does or did exist.
    */
    bool valid() const;
    explicit operator bool() const; //equivalent to this->valid()


    //Process Management Functions

    // detach a spawned process -- let it run after this handle destructs
    void detach();

    /** TODO clean... Terminate the child process. 
    *
    *  This function will cause the child process to unconditionally and immediately exit.
    *  It is implement with [SIGKILL](http://pubs.opengroup.org/onlinepubs/009695399/functions/kill.html) on posix
    *  and [TerminateProcess](https://technet.microsoft.com/en-us/library/ms686714.aspx) on windows.
    *
    */
    void terminate();

    // block until the process to exits 
    void wait();

    // block for the process to exit for a period of time.
    template< class Rep, class Period >
    bool wait_for  (const std::chrono::duration<Rep, Period>& rel_time);

    // wait for the process to exit until a point in time.
    template< class Clock, class Duration >
    bool wait_until(const std::chrono::time_point<Clock, Duration>& timeout_time );
    
    //The following is dependent on the networking TS. CompletionToken has the signature (int, std::error_code), i.e. wait for the process to exit and get the exit_code if exited. 
    template<class CompletionToken>
    DEDUCED async_wait(std::io_context & ctx, CompletionToken&& token);
};
#+END_SRC

** Class ~process_group~

#+BEGIN_SRC c++
class process_group
{
  public:
    //provides access to underlying operating system facilities
    typedef platform_specific native_handle_type; 

    process_group() = default;

    process_group(process_group && lhs);
    process_group& operator=(process_group && lhs);
 
    
    // The destructor terminates all processes in the group
    ~process_group();

    native_handle_type native_handle() const;


    // check if at least one process of the group is running
    bool running() const;

    /** Check if this handle holds a process group.
     * @note That does not mean, that the process is still running. It only means, that the handle does or did exist.
    */
    bool valid() const;
    explicit operator bool() const; //equivalent to this->valid()


    //Process Management Functions

    // detach a process group -- let it run after this handle destructs
    void detach();

    /** TODO clean... Terminate all the child processes. 
    *
    *  This function will cause the child process to unconditionally and immediately exit.
    *  It is implement with [SIGKILL](http://pubs.opengroup.org/onlinepubs/009695399/functions/kill.html) on posix
    *  and [TerminateProcess](https://technet.microsoft.com/en-us/library/ms686714.aspx) on windows.
    *
    */
    void terminate();

    // block until all processes exit
    void wait();

    // block until one process exit - note that windows does not yield information on which process exited.
    void wait_one();


    // block for all processes to exit for a period of time.
    template< class Rep, class Period >
    bool wait_for  (const std::chrono::duration<Rep, Period>& rel_time);

    // block for one process to exit for a period of time.
    template< class Rep, class Period >
    bool wait_for_one(const std::chrono::duration<Rep, Period>& rel_time);


    // wait for all processes to exit until a point in time.
    template< class Clock, class Duration >
    bool wait_until(const std::chrono::time_point<Clock, Duration>& timeout_time );
    

    // wait for one process to exit until a point in time.
    template< class Clock, class Duration >
    bool wait_until_one(const std::chrono::time_point<Clock, Duration>& timeout_time );
    
    //The following is dependent on the networking TS. CompletionToken has the signature (std::error_code) and waits for all processes to exit
    template<class CompletionToken>
    DEDUCED async_wait(std::io_context & ctx, CompletionToken&& token);

    //The following is dependent on the networking TS. CompletionToken has the signature (std::error_code) and waits for one process
    template<class CompletionToken>
    DEDUCED async_wait_one(std::io_context & ctx, CompletionToken&& token);

};
#+END_SRC

** Class ~process_io~

#+BEGIN_SRC c++
//satisfieds ProcessInitializer
/** This class describes I/O redirection for the standard-handles (stdin, stdout, stderr). They all are to be set, because windows either inherits all or all need ot be set. 
*/
class process_io
{
  //OS dependent handle type
  using native_handle * implementation-defined;
  
  struct  in_default { /* implementation-defined */ };
  struct out_default { /* implementation-defined */ };
  struct err_default { /* implementation-defined */ };
  //construct 
  template<typename In = in_default, typename Out = out_default, typename Err = err_default> 
  /* requires In to be ReadableStream, Out & Err to be WritableStream. 
  This is to be defined, but should allow any stream that can yield a system-handle (e.g. pipes, files & sockets) and to close the stream by passing nullptr. 
  Additionally a path should be possible to open a file just for the child process.
  */  
  process_io(In && in, Out && out, Err && err);
  
  /* Rest is implemtation defined */
};
#+END_SRC

** Class ~process_start_dir~

#+BEGIN_SRC c++
//satisfieds ProcessInitializer
/** This class the starting directory for the child process.
*/
class process_start_dir
{
  //Construct the initializer
  process_start_dir(const std::filesyste::path &);
 
};
#+END_SRC



** Enhanced ~system~ details

#+BEGIN_SRC c++
template<typename ...Args>
inline int system(Args && ... args)
{
    std::process c(std::forward<Args>(args)...,);
    if (!c.valid())
        return -1;
    c.wait();
    return c.exit_code();
}
#+END_SRC

** Extension of ~fstream~ 

The fstream/ofstream/ifstream classes shall have a member function that return the native handle of the opened file. (so process can use those for forwarding)

#+BEGIN_SRC c++
class fstream
{
/*....*/
public:
    typedef platform_specific native_handle_type; 
    native_handle_type native_handle() const;
};
#+END_SRC


* Open Questions
** if we don't have wait_for can we still detach? 

Yes.

** Can we piggyback on the thread's forward progress stuff for process as well? Can we assume all threads on the system behave like C++ threads? (Jeff - seems doubtful -- network TS)
** probably dont need process_args class - vector<string> fine

Yes. Range<string> would be better I (Klemens) think, so we can also use std::initializer_list<std::string> as in {"foo", "bar"}

** environment and command line
*** This proposal provides a use case for multiple instances of environment.  For process management there is the current process and child process environments -- not singleton from 1275
*** 1275 LEWGI in San Diego voted favoribly
*** From Klemens: std::this_process::environment though. That would make a few things more obvious, because we have an environment class too, that shuold just be used to set it up for the subprocess.
*** 1275 also has arguments does this work for our proposal?  The implementation is not complete for 1275. If the R1 has the environment as immutable then it will not work -- process needs to modify. 
*** args are available before main in 1275


* Acknowledgements

This proposal reflects the effort of the c++ community at C++Now 2019 and afterward. The primary participants are listed as authors on the paper, but many others participated in discussion of details during morning workshop sessions and conference breaks.  

None of this would have been possible without the work and guidance of Klemens Morgenstern, author of boost.process. 

* References
+ Isabella Muerte Desert Sessions: Improving hostile environment interactions http://wg21.link/p1275
+ boost.process documentation https://www.boost.org/libs/process 
+ Standard Library wishlist (Matt Austern) https://docs.google.com/document/d/1AC3vkOgFezPaeSZO-fvxgwzEIabw8I_seE7yFG_16Bk/preview
+ cppcast with Klemens on boost.process https://channel9.msdn.com/Shows/CppCast/Episode-72-BoostProcess-with-Klemens-Morgenstern
+ Pacific c++ Klemens on boost.process design https://www.youtube.com/watch?v=uZ4IG1OfeR0

